<?php session_start();
$page = 'gaestebuch_gast';
include('../inc/header.php');
echo "		<div class=\"bewertung-holder\">\n";
echo "			<h1 class=\"h1bewertung\"> Bewerten Sie unsere Dienstleistungen </h1>\n";
echo "		</div>\n";
echo "\n";
echo "		<a class=\"kerstellung\" id=\"zeige_kommentar_ersteller\" href=\"#\" onClick='(function(){\n";
echo "			document.getElementById(\"zeige_kommentar_ersteller\").style.visibility = \"hidden\";\n";
echo "			document.getElementById(\"kommentar_ersteller\").style.visibility = \"visible\";\n";
echo "		})(); return false;'>Neuen Eintrag verfassen</a>\n";
echo "		<div class=\"kommentarersteller\" id=\"kommentar_ersteller\">\n";
echo "			<form>\n";
echo "				<input placeholder=\"Titel\" /><br>\n";
echo "				<textarea class=\"comment\" placeholder=\"Kommentar\"></textarea><br>\n";
echo "				<input placeholder=\"Name\" /><br>\n";
echo "				<input type=\"submit\" value=\"Senden\" />\n";
echo "			</form>\n";
echo "		</div>\n";
echo "		<div class=\"comment-container\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Ganz ok</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Hätte mir einige weitere Funktionen gewünscht</p>\n";
echo "				<p class=\"kommentar_info_GB\">Von Manuel Bauer</p>\n";
echo "				<p class=\"kommentar_info_GB\">2. November 2020, 14:07</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Unglaublich gut</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Lernen ging nie einfacher!\n";
echo "				<p>\n";
echo "\n";
echo "				<p class=\"kommentar_info_GB\">Von Sabine Uhrmacher</p>\n";
echo "				<p class=\"kommentar_info_GB\">13. September 2020, 18:17</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Unverschämtheit</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Ich will mein Geld zurück, aber zackig!!!\n";
echo "				<p>\n";
echo "\n";
echo "				<p class=\"kommentar_info_GB\">Von Basti91</p>\n";
echo "				<p class=\"kommentar_info_GB\">22. Juli 2020, 10:03</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "		</div>\n";
echo "		<div class=\"pagination_GB\">\n";
echo "			<a href=\"#\">&laquo;</a>\n";
echo "			<a href=\"#\" class=\"active\">1</a>\n";
echo "			<a href=\"#\">2</a>\n";
echo "			<a href=\"#\">3</a>\n";
echo "			<a href=\"#\">&raquo;</a>\n";
echo "		</div>\n";
include('../inc/footer.php');
?>