<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"de\">\n";
echo "	<head>\n";
echo "		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style3.css\">\n";
echo "	    <link rel=\"stylesheet\" href='https://fonts.googleapis.com/css?family=Poppins'>\n";
echo "	    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n";
echo "	    <link rel=\"shortcut icon\" href=\"#\"/>\n";
echo "	    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "	    <meta charset=\"UTF-8\">\n";
echo "		<title> Kurs erstellen - Learnhub </title>\n";
echo "	</head>\n";
echo "	<body>\n";
echo "		<div class=\"fullscreen\">\n";
echo "			<nav>\n";
echo "				<div class=\"container\">\n";
echo "					<img class=\"logo\" alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "					<a title=\"hier finden sie nützliche Informationen über unsere Organisation\" href=\"proto_about-us.php\">Über uns</a>\n";
echo "					<a title=\"hier können sie zum Shop gelangen\" href=\"proto_shopansicht.php\">Shop</a>\n";
echo "					<a title=\"hier finden sie ihre erstellten Kurse\" class=\"active\" href=\"proto_erstellte_kurse.php\">erstellte Kurse</a>\n";
echo "					<a title=\"hier finden sie ihre gekauften Kurse\" href=\"proto_gekaufte_kurse.php\">gekaufte Kurse</a>\n";
echo "                    <a title=\"hier gelangen sie zum Gästebuch in dem User Bewertungen für die Seite hinterlassen können\" href=\"proto_gaestebuch.php\">Gästebuch</a>\n";
echo "					<a title=\"hier können sie sich ausloggen\" href=\"#abmelden\">abmelden</a>\n";
echo "                    <a class=\"a-abc\" href=\"#\"><img class=\"img-abc\" src=\"../bilder/abc.png\" alt=\"\" title=\"Font für Legastheniker benutzen\"></a>\n";
echo "				</div>\n";
echo "            </nav>\n";
echo "            <div class=\"col-wrapper\">\n";
echo "            <div class=\"column2 column-bg column-1\">\n";
echo "                <h1>Neuen Kurs erstellen\n";
echo "		    <form action=\"do.php\">\n";
echo "                    <input name=\"addCourse\" type=\"submit\" class=\"btn\" value=\"Erstellen\">\n";
echo "		    </form>\n";
echo "                  </h1>\n";
echo "                    <p>Titel des Kurses:</p>\n";
echo "                    <input name=\"title\" class=\"input-bg\" value=\"\">\n";
echo "                    <p class=\"pkurz\">Kurzbeschreibung (Wird auf der Startseite angezeigt):</p>\n";
echo "					<textarea name=\"summary\" class=\"txtarea\"></textarea>\n";
echo "    \n";
echo "					<p class=\"plernen\">Was kann man in diesem Kurs lernen?</p>\n";
echo "					<textarea name=\"educationalContent\" class=\"txtarea\"></textarea>\n";
echo "	\n";
echo "	\n";
echo "					<p class=\"pgoal\">Für wen ist dieser Kurs geeignet?</p>\n";
echo "					<textarea name=\"suitableFor\" class=\"txtarea\" >\n";
echo "					</textarea>\n";
echo "    	\n";
echo "	\n";
echo "			<br>\n";
echo "			<br>\n";
echo "			<fieldset>\n";
echo "				<legend> Zur Person, Kontaktmöglichkeiten </legend>\n";
echo "				<div class=\"kurststeller-holder\">\n";
echo "					<div class=\"kurssteller column-1\">\n";
echo "						<p>Name des Kurserstellers:</p>\n";
echo "						<input name=\"instructorName\" class=\"input-bg input-1\" value=\"\"/>\n";
echo "						<br>\n";
echo "						<p>Kontaktmöglichkeiten:</p>\n";
echo "						<textarea name=\"instructorContact\" class=\"txtarea\"></textarea>\n";
echo "\n";
echo "					</div>\n";
echo "					<div class=\"uploaded-img-wrapper column-2\">\n";
echo "						<p class=\"p-bg\">Bild des Kurserstellers:</p>\n";
echo "						<img alt=\"Platzhalter für ein Bild für den Kurs\" class=\"uploaded-img\" src=\"../bilder/noimage.png\"><br>\n";
echo "						<input name=\"instructorImage\" class=\"input-img\" type=\"file\">\n";
echo "					</div>\n";
echo "\n";
echo "\n";
echo "					<div class=\"place-holder\">\n";
echo "					</div>\n";
echo "				</div>\n";
echo "\n";
echo "			</fieldset>\n";
echo "			<br>\n";
echo "				<fieldset id=\"barrierefreiheit_fieldset\">\n";
echo "					<legend> Barrierefreiheit </legend>\n";
echo "\n";
echo "					<p class=\"p-learn\">Ist dieser Kurs für Sehbehinderte geeignet? <i class=\"fa fa-info-circle\" title=\"Dies ist beispielsweise der Fall, wenn visuelle Medien ausreichend per Text (für Screenreader) oder Stimme beschrieben werden.\"></i></p>\n";
echo "					<input type=\"radio\" id=\"sehbehinderteJa\" name=\"sehbehinderte\">\n";
echo "					<label for=\"sehbehinderteJa\"> Ja </label>\n";
echo "					<input type=\"radio\" id=\"sehbehinderteNein\" name=\"sehbehinderte\">\n";
echo "					<label for=\"sehbehinderteNein\"> Nein </label>\n";
echo "\n";
echo "					<p class=\"p-learn\">Ist dieser Kurs für Hörbehinderte geeignet? <i class=\"fa fa-info-circle\" title=\"Dies ist beispielsweise der Fall, wenn begleitend zu Audiomaterial (etwa in Videos) inhaltich ausreichender Text verfügbar ist.\"></i></p>\n";
echo "					<input type=\"radio\" id=\"hörbehindeteJa\" name=\"hörbehinderte\">\n";
echo "					<label for=\"hörbehindeteJa\"> Ja </label>\n";
echo "					<input type=\"radio\" id=\"hörbehinderteNein\" name=\"hörbehinderte\">\n";
echo "					<label for=\"hörbehinderteNein\"> Nein </label>\n";
echo "\n";
echo "\n";
echo "					<p class=\"p-learn\">Beschreibung des Kursbildes für Benutzer mit Screenreadern:</p>\n";
echo "					<input class=\"input-bg\" >\n";
echo "\n";
echo "\n";
echo "				</fieldset>\n";
echo "\n";
echo "                </div>\n";
echo "                <div class=\"column2 column-bg column-4 col-bg-3\">\n";
echo "                    <div class=\"upload-container\">\n";
echo "                        <div class=\"upload-wrapper\">\n";
echo "                                <p class=\"pupload-img\">Bild hochladen</p>\n";
echo "                            <img class=\"upload-img\" alt=\"Platzhalter für ein Bild vom Kursersteller\" src=\"../bilder/noimage.png\">\n";
echo "                        </div>\n";
echo "                        <p id=\"preisdisplay\"> <strong class=\"price\"> Preis: 89,99€ </strong></p>\n";
echo "                        <p> Euro: <input onchange=\"euroChanged()\" id=\"europicker\" class=\"u-currency currency\" type=\"number\" min=\"1\" step=\"any\" value=\"89\" /></p>\n";
echo "                        <p> Cent: <input onchange=\"centChanged()\" id=\"centpicker\" class=\"c-currency currency\" type=\"number\" min=\"1\" max=\"99\" step=\"any\" value=\"99\"/></p>\n";
echo "                        <!-- <script>\n";
echo "        \n";
echo "                            function updatePreis(preistext)\n";
echo "                            {\n";
echo "                                document.getElementById(\"preisdisplay\").innerText  = preistext\n";
echo "                            }\n";
echo "        \n";
echo "                            function euroChanged()\n";
echo "                            {\n";
echo "                                updatePreis(\"Preis: \" + document.getElementById(\"europicker\").value + \",\" + document.getElementById(\"centpicker\").value + \"€\");\n";
echo "                            }\n";
echo "        \n";
echo "                            function centChanged()\n";
echo "                            {\n";
echo "                                updatePreis(\"Preis: \" + document.getElementById(\"europicker\").value + \",\" + document.getElementById(\"centpicker\").value + \"€\");\n";
echo "                            }\n";
echo "        \n";
echo "                            \n";
echo "                        </script> -->\n";
echo "        \n";
echo "                        <br>\n";
echo "                        <p>Was ist in diesem Kurs enthalten?</p>\n";
echo "                        <textarea name=\"materialContent\" class=\"txtarea\" ></textarea>\n";
echo "                    </div> \n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <footer class=\"footer-distributed\">\n";
echo "\n";
echo "                <div class=\"footer-left\">\n";
echo "                    <img alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "                    <h3>About<span class=\"learn\">Learn</span><span class=\"hub\"><mark>hub</mark></span></h3>\n";
echo "    \n";
echo "                    <p class=\"footer-company-name\">© 2020 E-Learning Platform. Ltd.</p>\n";
echo "                </div>\n";
echo "    \n";
echo "                <div class=\"footer-center\">\n";
echo "                    <div>\n";
echo "                        <i class=\"fa fa-map-marker\"></i>\n";
echo "                        <p><span>Hochschule</span>\n";
echo "                            Trier</p>\n";
echo "                    </div>\n";
echo "                    <div>\n";
echo "                        <i class=\"fa fa-envelope\"></i>\n";
echo "                        <p><a href=\"ismailj@hochschule-trier.de\">ismailj@hochschule-trier.de</a></p>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"footer-right\">\n";
echo "                    <p class=\"footer-company-about\">\n";
echo "                        <span>Über das Unternehmen</span>\n";
echo "					Wir bieten Schulungen und Kurse zum Aufbau von Fähigkeiten in den Bereichen Technologie, Design, Business und Wissenschaft an\n";
echo "					</p>\n";
echo "                    <div class=\"footer-icons\">\n";
echo "                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n";
echo "                        <a href=\"#\"><i class=\"fa fa-youtube\"></i></a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </footer>\n";
echo "        </div>\n";
echo "        </body>\n";
echo "        </html>\n";
?>