<?php session_start();
$page = 'bearbeitung';
include('../inc/header.php');
echo "            <div class=\"col-wrapper\">\n";
echo "            <div class=\"column2 column-bg column-1\">\n";
echo "                <h1>Kursbearbeitung\n";
echo "                    <input type=\"submit\" class=\"btn\" value=\"Änderungen verwerfen\">\n";
echo "		    <form action=\"do.php\">\n";
echo "                    <input name=\"editCourse\" type=\"submit\" class=\"btn\" value=\"Speichern\">\n";
echo "		    <input type=\"hidden\" name=\"id\">\n";
echo "		    </form>\n";
echo "                  </h1>\n";
echo "                    <p>Titel des Kurses:</p>\n";
echo "                    <input name=\"title\" class=\"input-bg\" value=\"Java 101: Das Sprungbrett für Einsteiger\">\n";
echo "                    <p class=\"pkurz\">Kurzbeschreibung (Wird auf der Startseite angezeigt):</p>\n";
echo "					<textarea name=\"summary\" class=\"txtarea\">Java ist eine besondere Programmiersprache, die sich an der Syntax der Programmiersprachen C und C++ anlehnt. \n";
echo "					Bei der Entwicklung von Java wurde von Beginn an genauestens darauf geachtet, dass bestimmte schwere Programmierfehler erst gar nicht auftreten können. \n";
echo "					In diesem Einsteigerkurs lernen sie die Grundlagen der Sprache kennen und machen sich vertraut mit dem Code schreiben.</textarea>\n";
echo "					\n";
echo "					<p class=\"plernen\">Was kann man in diesem Kurs lernen?</p>\n";
echo "									<textarea name=\"educationalContent\" class=\"txtarea\">✔ Umfangreiche Java Grundlagen kennen lernen und eigene Programme entwickeln\n";
echo "					✔ Die Programmiersprache Java verstehen und anwenden können\n";
echo "					✔ Perfekte Grundlagen um Android Apps mit Java zu programmieren \n";
echo "					✔ Grundkenntnisse der objektorientierten Java Programmierung lernen\n";
echo "					✔ Übungsaufgaben mit Lösungen nach jedem Videoblock und das Gelernte Wissen mit Java umzusetzen\n";
echo "					✔ Keine langweilige Theorie, sondern echte Beispiele aus der Praxis\n";
echo "					✔ Du lernst alle Vorteile von Java gegenüber anderen Programmiersprachen kennen\n";
echo "					✔ Einführung in JavaFX um eigene visuelle Oberflächen zu erstellen\n";
echo "					✔ Über 30 Stunden Video-Inhalt und 127 Java Lektionen</textarea>\n";
echo "					\n";
echo "					\n";
echo "									<p class=\"pgoal\">Für wen ist dieser Kurs geeignet?</p>\n";
echo "									<textarea name=\"suitableFor\" class=\"txtarea\" >\n";
echo "					- Jeder der Java lernen will\n";
echo "					- Jeder der Interesse an Java hat\n";
echo "					- Jeder der eine starke Grundlage für die Programmierung von Android Apps schaffen will\n";
echo "					- Alle, die Java endlich lernen und verstehen wollen\n";
echo "					</textarea>\n";
echo "						\n";
echo "					\n";
echo "				<br>\n";
echo "				<br>\n";
echo "				<fieldset>\n";
echo "					<legend> Zur Person, Kontaktmöglichkeiten </legend>\n";
echo "					<div class=\"kurststeller-holder\">\n";
echo "						<div class=\"kurssteller column-1\">\n";
echo "							<p>Name des Kurserstellers:</p>\n";
echo "							<input name=\"instructorName\" class=\"input-bg input-1\" value=\"Prof. Dr. Simon. Steinmetz\"/>\n";
echo "							<br>\n";
echo "							<p>Kontaktmöglichkeiten:</p>\n";
echo "							<textarea name=\"instructorContact\" class=\"txtarea\">+49 651 8103-316\n";
echo "				+49 651 8103-454\n";
echo "				S.steinmetz(at)hochschule-trier.de </textarea>\n";
echo "\n";
echo "						</div>\n";
echo "						<div class=\"uploaded-img-wrapper column-2\">\n";
echo "							<img class=\"uploaded-img\" alt=\"Platzhalter für das Bild des Erstellers\" src=\"../bilder/simon.png\"><br>\n";
echo "							<input name=\"instructorImage\" class=\"input-img\" type=\"file\">\n";
echo "						</div>\n";
echo "\n";
echo "\n";
echo "						<div class=\"place-holder\">\n";
echo "						</div>\n";
echo "					</div>\n";
echo "\n";
echo "				</fieldset>\n";
echo "				<br>\n";
echo "								</div>\n";
echo "                <div class=\"column2 column-bg column-4 col-bg-3\">\n";
echo "                    <div class=\"upload-container\">\n";
echo "                        <div class=\"upload-wrapper\">\n";
echo "                                <p class=\"pupload-img\">Bild hochladen</p>\n";
echo "                            <img class=\"upload-img\" alt=\"Platzhalter für das Bild des Kurses\" src=\"../bilder/java.jpg\">\n";
echo "                        </div>\n";
echo "                        <p id=\"preisdisplay\"> <strong class=\"price\"> Preis: 89,99€ </strong></p>\n";
echo "                        <p> Euro: <input onchange=\"euroChanged()\" id=\"europicker\" class=\"u-currency currency\" type=\"number\" min=\"1\" step=\"any\" value=\"89\" /></p>\n";
echo "                        <p> Cent: <input onchange=\"centChanged()\" id=\"centpicker\" class=\"c-currency currency\" type=\"number\" min=\"1\" max=\"99\" step=\"any\" value=\"99\"/></p>\n";
echo "                        <!-- <script>\n";
echo "        \n";
echo "                            function updatePreis(preistext)\n";
echo "                            {\n";
echo "                                document.getElementById(\"preisdisplay\").innerText  = preistext\n";
echo "                            }\n";
echo "        \n";
echo "                            function euroChanged()\n";
echo "                            {\n";
echo "                                updatePreis(\"Preis: \" + document.getElementById(\"europicker\").value + \",\" + document.getElementById(\"centpicker\").value + \"€\");\n";
echo "                            }\n";
echo "        \n";
echo "                            function centChanged()\n";
echo "                            {\n";
echo "                                updatePreis(\"Preis: \" + document.getElementById(\"europicker\").value + \",\" + document.getElementById(\"centpicker\").value + \"€\");\n";
echo "                            }\n";
echo "        \n";
echo "                            \n";
echo "                        </script> -->\n";
echo "        \n";
echo "                        <br>\n";
echo "                        <p>Was ist in diesem Kurs enthalten?</p>\n";
echo "                        <textarea name=\"materialContent\" class=\"txtarea\" >- 29 Stunden On-Demand-Video \n";
echo "						- 3 Artikel\n";
echo "						- 26 zum Download verfügbare Materialien\n";
echo "						- Uneingeschränkter lebenslanger Zugriff\n";
echo "						- Zugriff auf Handy/Tablet und TV \n";
echo "						- Abschlussbescheinigung</textarea>\n";
echo "                    </div> \n";
echo "                </div>\n";
echo "            </div>\n";
include('../inc/footer.php');
?>