<?php session_start();
$page = 'nichtteilnehmender';
include('../inc/header.php');
echo "        <div class=\"main-container\">\n";
echo "            <div class=\"main-wrapper\">\n";
echo "                <div class=\"description-container column-8\">\n";
echo "                    <h1 class=\"h1-java\"> Java 101: Das Sprungbrett für Einsteiger</h1>\n";
echo "                    <p class=\"p-description\"> Java ist eine besondere Programmiersprache, die sich an <br>\n";
echo "                        der Syntax der Programmiersprachen C und C++ anlehnt. Bei der <br>\n";
echo "                        Entwicklung von Java wurde von Beginn an genauestens darauf <br>\n";
echo "                        geachtet, dass bestimmte schwere Programmierfehler erst gar nicht <br>\n";
echo "                        auftreten können. In diesem Einsteigerkurs lernen sie die Grundlagen <br>\n";
echo "                        der Sprache kennen und machen sich vertraut mit dem Code schreiben. </p>\n";
echo "                </div>\n";
echo "                <div class=\"img-container column-9\">\n";
echo "                    <img class=\"img-kurs\"\n";
echo "                        alt=\"Kursbild zum Kurs Python Bootcamp: Vom Anfäner zum Profi, un nur 2 Monaten. <Beschreibung>.\"\n";
echo "                        src=\"../bilder/java.jpg\"><br>\n";
echo "                        <p> <strong class=\"preis-strong\"> Preis: 89,99€ </strong></p><br>\n";
echo "			<form action=\"do.php\">\n";
echo "                        <input name=\"buyCourse\" type=\"submit\" class=\"btn\" value=\"Kaufen\">\n";
echo "			<input name=\"id\" type=\"hidden\">\n";
echo "			</form>\n";
echo "                    <!-- <form action=\"proto_kurs-bearbeitung.php\"> <input type=\"submit\" value=\"Kurs bearbeiten\"> </form> -->\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"col-wrapper\">\n";
echo "            <div class=\"column2 column-bg column-1\">\n";
echo "                <div class=\"learn-container\">\n";
echo "                      <h2 class=\"h2-teilnehmer\"> Das wirst du lernen </h2>\n";
echo "                        ✔ Umfangreiche Java Grundlagen kennen lernen und eigene Programme entwickeln <br> <br>\n";
echo "                        ✔ Die Programmiersprache Java verstehen und anwenden können <br><br>\n";
echo "                        ✔ Perfekte Grundlagen um Android Apps mit Java zu programmieren <br><br>\n";
echo "                        ✔ Grundkenntnisse der objektorientierten Java Programmierung lernen <br><br>\n";
echo "                        ✔ Übungsaufgaben mit Lösungen nach jedem Videoblock und das Gelernte Wissen mit Java umzusetzen\n";
echo "                        <br><br>\n";
echo "                        ✔ Keine langweilige Theorie, sondern echte Beispiele aus der Praxis <br><br>\n";
echo "                        ✔ Du lernst alle Vorteile von Java gegenüber anderen Programmiersprachen kennen <br><br>\n";
echo "                        ✔ Einführung in JavaFX um eigene visuelle Oberflächen zu erstellen <br><br>\n";
echo "                        ✔ Über 30 Stunden Video-Inhalt und 127 Java Lektionen <br><br>\n";
echo "                    <h2 class=\"h2-teilnehmer\"> Für wen eignet sich dieser Kurs? </h2>\n";
echo "                    <p class=\"p-bg\">\n";
echo "                        - Jeder der Java lernen will <br>\n";
echo "                        - Jeder der Interesse an Java hat <br>\n";
echo "                        - Jeder der eine starke Grundlage für die Programmierung von Android Apps schaffen will <br>\n";
echo "                        - Alle, die Java endlich lernen und verstehen wollen</p>\n";
echo "                </div>\n";
echo "                <div class=\"barrier-container\">\n";
echo "                    <h2 class=\"h2-teilnehmer\"> Barrierefreiheit </h2>\n";
echo "                    <p class=\"p-bg\"> Dieser Kurs ist für Sehbehinderte geeignet</p>\n";
echo "                    <p class=\"p-bg\"> Dieser Kurs ist leider nicht für Hörbehinderte geeignet</p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"column2 column-bg column-4 col-bg-3 col-enthalten\">\n";
echo "                    <div class=\"enthalten-bg\">\n";
echo "                    <p class=\"p-bg\"> <strong class=\"strong-enthalten\"> Das ist im Kurs enthalten </strong> <br>\n";
echo "                        - 29 Stunden On-Demand-Video <br>\n";
echo "                        - 3 Artikel <br>\n";
echo "                        - 26 zum Download verfügbare Materialien <br>\n";
echo "                        - Uneingeschränkter lebenslanger Zugriff <br>\n";
echo "                        - Zugriff auf Handy/Tablet und TV <br>\n";
echo "                        - Abschlussbescheinigung </p>\n";
echo "                    </div>\n";
echo "                    <div class=\"contact-container\">\n";
echo "                        <h2 class=\"h2-teilnehmer\"> Kontakt und Beratung </h2>\n";
echo "                        <img class=\"img-teacher\" alt=\"Bild des Kurserstellers\" src=\"../bilder/simon.png\">\n";
echo "                        <p class=\"p-bg\"> <strong class=\"strong-name\"> Prof. Dr. Simon Steinmetz </strong> <br>\n";
echo "                            Ersteller des Kurses <br> <br>\n";
echo "                            Kontakt <br>\n";
echo "                            +49 651 8103-316 <br>\n";
echo "                            +49 651 8103-454 <br>\n";
echo "                            S.steinmetz@hochschule-trier.de <br></p>\n";
echo "                    </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"review-container\">\n";
echo "            <h2 class=\"h2-teilnehmer\"> Bewertungen von Teilnehmern dieses Kurses </h2>\n";
echo "            <div class=\"columns-3\">\n";
echo "                <div class=\"col-7\">\n";
echo "                    <img class=\"user-img\" alt=\"Bild eines Benutzers\" src=\"../bilder/user_bewertung1.png\">\n";
echo "                </div>\n";
echo "                <div class=\"col-6\">\n";
echo "                    <p class=\"bewertung_k_nB\"> <strong> mxtr0669@hochschule-trier.de: </strong> <br>\n";
echo "                        Ein wirklich sehr schöner Kurs. <br>\n";
echo "                        Die Themen sind sehr pragmatisch und sauber erklärt. Man kann gut folgen und die Umsetzung in den\n";
echo "                        Tools ich wirklich gut gelungen. <br>\n";
echo "                        Ich habe parallel meine eigenen Beispiele umsetzen können. Vielen Dank. </p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"columns-3\">\n";
echo "                <div class=\"col-7\">\n";
echo "                    <img class=\"user-img\" alt=\"Bild eines Benutzers\" src=\"../bilder/user_bewertung2.png\">\n";
echo "                </div>\n";
echo "                <div class=\"col-6\">\n";
echo "                    <p class=\"bewertung_k_nB\"> <strong> ismailj@hochschule-trier.de: </strong> <br>\n";
echo "                        Als Einführung in Java war dieser Kurs sehr gut, <br> \n";
echo "                        vor allem die Entwicklung kleiner Programme hat mir sehr gefallen. <br> \n";
echo "                        Da ich vorher schon Fortran und Python gelernt habe, hat sich für mich einiges wiederholt.\n";
echo "                        Z.b. wie Schleifen funktionieren oder die <br> allgemeine Programmierlogik. </p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"columns-3\">\n";
echo "                <div class=\"col-7\">\n";
echo "                    <img class=\"user-img\" alt=\"Bild eines Benutzers\" src=\"../bilder/user_bewertung3.png\">\n";
echo "                </div>\n";
echo "                <div class=\"col-6\">\n";
echo "                    <p class=\"bewertung_k_nB\"> <strong> leomathys@hochschule-trier.de: </strong> <br>\n";
echo "                        Anfangs sehr gut, dann bißchen zu schnell. <br>\n";
echo "                        Es wäre gut, wenn man einiges zusammen fasst und \"richtige\" Programme schreiben würde \n";
echo "                        um den gesamten Zusammenhang besser <br> verstehen bzw. nachvollziehen zu können. </p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
include('../inc/footer.php');
?>