<?php session_start(); 
$page = 'shop';
include('../inc/header.php');
echo "            <div class=\"search-bar\">\n";
echo "				<h1>Hier finden Sie angebotene Kurse </h1>\n";
echo "					<input class=\"search-input\" placeholder=\"Suche nach Begriff...\">\n";
echo "					<noscript>\n";
echo "						<p class=\"nojavascriptmsg\">Suchfunktion nur mit Javascript möglich!</p>\n";
echo "					</noscript>\n";
echo "			</div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Java 101: Das Sprungbrett für Einsteiger.\" src=\"../bilder/python.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                            <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u> Java 101: Das Sprungbrett für Einsteiger </u> </strong> </h3> \n";
echo "                                                    Java ist eine besondere Programmiersprache, die sich an <br> \n";
echo "                                                    der Syntax der Programmiersprachen C und C++ anlehnt. Bei der <br> \n";
echo "                                                    Entwicklung von Java wurde von Beginn an genauestens darauf <br> \n";
echo "                                                    geachtet, dass bestimmte schwere Programmierfehler erst gar nicht <br>\n";
echo "                                                    auftreten können.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Simon Steinmetz <br>\n";
echo "                                                Preis: 89,99€</p><br>\n";
echo "						<form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Python Bootcamp: Vom Anfäner zum Profi, un nur 2 Monaten.\" src=\"../bilder/java.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                            <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u>  Python Bootcamp: Vom Anfänger zum Profi,in nur 2 Monaten. </u> </strong> </h3> \n";
echo "                                                    Die Syntax der Sprache ist sehr einfach und leicht zu verstehen <br> \n";
echo "                                                    und die Länge des Codes ist relativ kurz. Es macht meist auch für <br> \n";
echo "                                                    Anfänger viel Spaß, sich mit Python zu beschäftigen, weil du dich ganz <br> \n";
echo "                                                    auf die Lösung des Problems konzentrieren kannst, statt dich mit Besonderheiten\n";
echo "                                                    der Sprache herumzuschlagen.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Leo Mathys <br>\n";
echo "                                                Preis: 119,99€</p><br>\n";
echo "                                                <form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Einstieg in die Technologien des WWW.\" src=\"../bilder/web-entwicklung.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                         <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u> Einstieg in die Technologien des WWW </u> </strong> </h3> \n";
echo "                                                    Seit der Kommerzialisierung des Internets Anfang der 1990er Jahre <br>\n";
echo "                                                    unterliegt die Webentwicklung einem ständigen Wandel. Waren Internetseiten \n";
echo "                                                    früher als Ansammlungen schmuckloser Textfelder <br> angelegt, steht heute eine \n";
echo "                                                    aufwendige Präsentation multimedialer <br> Inhalte im Vordergrund.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Nicolas Arend <br>\n";
echo "                                                Preis: 499,99€</p><br>\n";
echo "						<form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
include('../inc/footer.php');
?>