<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"de\">\n";
echo "	<head>\n";
echo "		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style3.css\">\n";
echo "	    <link rel=\"stylesheet\" href='https://fonts.googleapis.com/css?family=Poppins'>\n";
echo "	    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n";
echo "	    <link rel=\"shortcut icon\" href=\"#\"/>\n";
echo "	    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "	    <meta charset=\"UTF-8\">\n";
echo "		<title> Shop - Learnhub </title>\n";
echo "	</head>\n";
echo "	<body>\n";
echo "		<div class=\"fullscreen\">\n";
echo "			<nav>\n";
echo "				<div class=\"container\">\n";
echo "					<img class=\"logo\" alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "					<a title=\"hier finden sie nützliche Informationen über unsere Organisation\" href=\"proto_about-us.php\">Über uns</a>\n";
echo "					<a title=\"hier können sie zum Shop gelangen\" class=\"active\" href=\"proto_shopansicht.php\">Shop</a>\n";
echo "					<a title=\"hier finden sie ihre erstellten Kurse\" href=\"proto_erstellte_kurse.php\">erstellte Kurse</a>\n";
echo "					<a title=\"hier finden sie ihre gekauften Kurse\" href=\"proto_gekaufte_kurse.php\">gekaufte Kurse</a>\n";
echo "					<a title=\"hier gelangen sie zum Gästebuch in dem User Bewertungen für die Seite hinterlassen können\" href=\"proto_gaestebuch.php\">Gästebuch</a>\n";
echo "					<a title=\"hier können sie sich ausloggen\" href=\"#abmelden\">abmelden</a>\n";
echo "					<a class=\"a-abc\" href=\"#\"><img class=\"img-abc\" src=\"../bilder/abc.png\" alt=\"\" title=\"Font für Legastheniker benutzen\"></a>\n";
echo "				</div>\n";
echo "            </nav>\n";
echo "            <div class=\"search-bar\">\n";
echo "				<h1>Hier finden Sie angebotene Kurse </h1>\n";
echo "					<input class=\"search-input\" placeholder=\"Suche nach Begriff...\">\n";
echo "					<noscript>\n";
echo "						<p class=\"nojavascriptmsg\">Suchfunktion nur mit Javascript möglich!</p>\n";
echo "					</noscript>\n";
echo "			</div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Java 101: Das Sprungbrett für Einsteiger.\" src=\"../bilder/python.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                            <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u> Java 101: Das Sprungbrett für Einsteiger </u> </strong> </h3> \n";
echo "                                                    Java ist eine besondere Programmiersprache, die sich an <br> \n";
echo "                                                    der Syntax der Programmiersprachen C und C++ anlehnt. Bei der <br> \n";
echo "                                                    Entwicklung von Java wurde von Beginn an genauestens darauf <br> \n";
echo "                                                    geachtet, dass bestimmte schwere Programmierfehler erst gar nicht <br>\n";
echo "                                                    auftreten können.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Simon Steinmetz <br>\n";
echo "                                                Preis: 89,99€</p><br>\n";
echo "						<form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Python Bootcamp: Vom Anfäner zum Profi, un nur 2 Monaten.\" src=\"../bilder/java.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                            <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u>  Python Bootcamp: Vom Anfänger zum Profi,in nur 2 Monaten. </u> </strong> </h3> \n";
echo "                                                    Die Syntax der Sprache ist sehr einfach und leicht zu verstehen <br> \n";
echo "                                                    und die Länge des Codes ist relativ kurz. Es macht meist auch für <br> \n";
echo "                                                    Anfänger viel Spaß, sich mit Python zu beschäftigen, weil du dich ganz <br> \n";
echo "                                                    auf die Lösung des Problems konzentrieren kannst, statt dich mit Besonderheiten\n";
echo "                                                    der Sprache herumzuschlagen.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Leo Mathys <br>\n";
echo "                                                Preis: 119,99€</p><br>\n";
echo "                                                <form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"columns column-66\">\n";
echo "                    <div class=\"col-21\">\n";
echo "                        <a class=\"kurs_link_EK\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\">\n";
echo "                            <img class=\"kurs_box_EK\" alt=\"Kursbild zum Kurs Einstieg in die Technologien des WWW.\" src=\"../bilder/web-entwicklung.png\"></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-69\">\n";
echo "                         <a class=\"p-420\" href=\"proto_kursansicht_nichtteilnehmender-Benutzer.php\"> <h3> <strong> <u> Einstieg in die Technologien des WWW </u> </strong> </h3> \n";
echo "                                                    Seit der Kommerzialisierung des Internets Anfang der 1990er Jahre <br>\n";
echo "                                                    unterliegt die Webentwicklung einem ständigen Wandel. Waren Internetseiten \n";
echo "                                                    früher als Ansammlungen schmuckloser Textfelder <br> angelegt, steht heute eine \n";
echo "                                                    aufwendige Präsentation multimedialer <br> Inhalte im Vordergrund.</a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-420\"><p class=\"p-bg\">\n";
echo "                        Ersteller: Prof. Dr. Nicolas Arend <br>\n";
echo "                                                Preis: 499,99€</p><br>\n";
echo "						<form action=\"do.php\">\n";
echo "                                                <input name=\"buyCourse\" type=\"submit\" class=\"btn-purchase\" value=\"Kurs kaufen\">\n";
echo "						<input type=\"hidden\" name=\"id\">\n";
echo "						</form>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "			<footer class=\"footer-distributed\">\n";
echo "\n";
echo "				<div class=\"footer-left\">\n";
echo "					<img alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "					<h3>About<span class=\"learn\">Learn</span><span class=\"hub\"><mark>hub</mark></span></h3>\n";
echo "	\n";
echo "					<p class=\"footer-company-name\">© 2020 E-Learning Platform. Ltd.</p>\n";
echo "				</div>\n";
echo "	\n";
echo "				<div class=\"footer-center\">\n";
echo "					<div>\n";
echo "						<i class=\"fa fa-map-marker\"></i>\n";
echo "						<p><span>Hochschule</span>\n";
echo "							Trier</p>\n";
echo "					</div>\n";
echo "					<div>\n";
echo "						<i class=\"fa fa-envelope\"></i>\n";
echo "						<p><a href=\"ismailj@hochschule-trier.de\">ismailj@hochschule-trier.de</a></p>\n";
echo "						<!-- <i class=\"fa fa-envelope\"></i>\n";
echo "						<p><a href=\"mxtr0669@hochschule-trier.de\">mxtr0669@hochschule-trier.de</a></p>\n";
echo "						<i class=\"fa fa-envelope\"></i>\n";
echo "						<p><a href=\"fachriw@hochschule-trier.de\">fachriw@hochschule-trier.de</a></p> -->\n";
echo "					</div>\n";
echo "				</div>\n";
echo "				<div class=\"footer-right\">\n";
echo "					<p class=\"footer-company-about\">\n";
echo "						<span>Über das Unternehmen</span>\n";
echo "					Wir bieten Schulungen und Kurse zum Aufbau von Fähigkeiten in den Bereichen Technologie, Design, Business und Wissenschaft an\n";
echo "					</p>\n";
echo "					<div class=\"footer-icons\">\n";
echo "						<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n";
echo "						<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n";
echo "						<a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n";
echo "						<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n";
echo "						<a href=\"#\"><i class=\"fa fa-youtube\"></i></a>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</footer>\n";
echo "		</div>\n";
echo "	</body>\n";
echo "</html>\n";
?>