<?php
echo "<DOCTYPE html>\n";
echo "<html lang=\"de\">\n";
echo "\n";
echo "<head>\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style3.css\">\n";
echo "	<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Poppins\">\n";
echo "	<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n";
echo "	<link rel=\"shortcut icon\" href=\"#\"/>\n";
echo "	<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "	<meta charset=\"UTF-8\">\n";
echo "	<title> About-us - Learnhub </title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "	<div class=\"fullscreen\">\n";
echo "		<nav>\n";
echo "            <div class=\"container\">\n";
echo "                <img class=\"logo\" alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "                <a title=\"hier finden sie nützliche Informationen über unsere Organisation\" class=\"active\" href=\"proto_about-us.php\">Über uns</a>\n";
echo "                <a title=\"hier können sie zum Shop gelangen\" href=\"proto_shopansicht.php\">Shop</a>\n";
echo "                <a title=\"hier finden sie ihre erstellten Kurse\" href=\"proto_erstellte_kurse.php\">erstellte Kurse</a>\n";
echo "                <a title=\"hier finden sie ihre gekauften Kurse\" href=\"proto_gekaufte_kurse.php\">gekaufte Kurse</a>\n";
echo "                <a title=\"hier gelangen sie zum Gästebuch in dem User Bewertungen für die Seite hinterlassen können\" href=\"proto_gaestebuch.php\">Gästebuch</a>\n";
echo "                <a title=\"hier können sie sich ausloggen\" href=\"#abmelden\">abmelden</a>\n";
echo "                <a class=\"a-abc\" href=\"#\"><img class=\"img-abc\" src=\"../bilder/abc.png\" alt=\"\" title=\"Font für Legastheniker benutzen\"></a>\n";
echo "            </div>\n";
echo "        </nav>\n";
echo "\n";
echo "        <div class=\"columns columns-bg-1\">\n";
echo "            <div class=\"col-1 col-bg col-bg-1\">\n";
echo "				<h1> Über uns </h1>\n";
echo "                <h2> Lernen, wo und wann du willst: <br> Leg noch heute los mit Learnhub!</h2>\n";
echo "			</div>\n";
echo "			<div class=\"col-1 col-bg-2\">\n";
echo "				<p> Learnhub hilft seinen Benutzern mit den rasanten  \n";
echo "				Veränderungen der Arbeitswelt Schritt zu halten. Unsere sorgfältig ausgewählte  \n";
echo "				und gepflegte Zusammenstellung von top-bewerteten Kursen zu Business, Design, \n";
echo "				Marketing, IT und vielen mehr möglichen\n";
echo "				Themen unterstützt unsere Benutzer, sich \n";
echo "				gezielt weiterzubilden und ihnen gleichzeitig Ressourcen zur \n";
echo "				eigenständigen Weiterentwicklung an die Hand zu geben.\n";
echo "				Qualitativ hochwertige Inhalte allein reichen nicht aus. Unser \n";
echo "				Marktplatz-Inhaltsmodell stellt sicher, dass wir immer über die \n";
echo "				neuesten und qualitativ hochwertigsten Inhalte verfügen, die das \n";
echo "				Lernen angenehm machen.\n";
echo "				</p>\n";
echo "			</div>\n";
echo "        </div>\n";
echo "        <div class=\"columns\">\n";
echo "            <div class=\"col-2 col-bg col-img\">\n";
echo "            <img class=\"banner-img\" src=\"../bilder/learning3.jpg\" alt=\"Banner zur Dekoration der Seite. Auf dem Bild sind Reihen von Tablets, die jeweils Präsentationsfolien zu unterschiedlichen  Technologien anzeigen.\">\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"columns columns-bg-1\">\n";
echo "            <div class=\"col-3 col-bg col-bg-3\">\n";
echo "            <p> <h2> Unsere Vision </h2>\n";
echo "                Learnhub verbindet wissenshungrige Menschen in der ganzen Welt mit <br>\n";
echo "				fantastischen Lehrern und gibt damit jedem die Chance, seine Ziele zu <br> \n";
echo "				erreichen und seine Träume zu verwirklichen. Benutzer aus der ganzen Welt leben unsere \n";
echo "				Werte gerade vorbildlich: Sie lieben es, jeden Tag etwas Neues zu lernen <br> \n";
echo "				und geben ihr Wissen genauso gerne an andere weiter. Wir legen großen <br> \n";
echo "				Wert auf Diversität und Inklusion und die persönliche und berufliche <br> \n";
echo "				Weiterentwicklung jedes Einzelnen. Neue Herausforderungen sind unsere <br>\n";
echo "				größte Motivation und natürlich: Wir lieben Learnhub-Kurse!\n";
echo "				\n";
echo "	    </div>\n";
echo "            <div class=\"col-1 col-bg\">\n";
echo "            <img class=\"learn-img\" src=\"../bilder/learning4.png\" alt=\"Links vier Bücher, eines davon aufgeklappt. Rechts eine Cartoonfigur mit aufgeklapptem Kopf. Eine Ansammlung aus Symbolen strömt aus dem aufgeklappten Buch in den Kopf der Cartoonfigur.\">\n";
echo "        </div>\n";
echo "        </div>\n";
echo "        <div class=\"columns\">\n";
echo "            <div class=\"col-4 col-bg col-bg-2 col-bg-4\">\n";
echo "            <h1> Wir sind ein Team aus drei ambitionierten Studenten 8) </h1><br>\n";
echo "            <p> Schon von jung an, war es unser Ziel, unseren Mitmenschen einen Weg zu zeigen, um sich\n";
echo "                weiterbilden zu können </p>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <div class=\"row\">\n";
echo "            <div class=\"column\">\n";
echo "                <img class=\"img-bg\" src=\"../bilder/joud.png\" alt=\"Gesicht von Joud Ismail überklebt auf das Gesicht eines Arm verschränkenden Geschäftsmannes.\">\n";
echo "                <div class=\"overlay\">Joud Ismail - Senior Coder</div>\n";
echo "            </div>\n";
echo "            <div class=\"column\">\n";
echo "                <img class=\"img-bg\" src=\"../bilder/maxi.png\" alt=\"Gesicht von Maximilian Trinkaus überklebt auf das Gesicht eines Arm verschränkenden Geschäftsmannes.\">\n";
echo "                <div class=\"overlay\">Maximilian Trinkaus - Senior Designer</div>\n";
echo "            </div>\n";
echo "            <div class=\"column\">\n";
echo "                <img class=\"img-bg\" src=\"../bilder/walid.png\" alt=\"Gesicht von Walid Fachri überklebt auf das Gesicht eines Arm verschränkenden Geschäftsmannes\">\n";
echo "                <div class=\"overlay\">Walid Fachri - Senior Project-Manager</div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <footer class=\"footer-distributed\">\n";
echo "\n";
echo "			<div class=\"footer-left\">\n";
echo "				<img alt=\"leanhublogo\" src=\"../bilder/learnhublogo.png\">\n";
echo "				<h3>About<span class=\"learn\">Learn</span><span class=\"hub\"><mark>hub</mark></span></h3>\n";
echo "\n";
echo "				<p class=\"footer-company-name\">© 2020 E-Learning Platform. Ltd.</p>\n";
echo "			</div>\n";
echo "\n";
echo "			<div class=\"footer-center\">\n";
echo "				<div>\n";
echo "					<i class=\"fa fa-map-marker\"></i>\n";
echo "					<p><span>Hochschule</span>\n";
echo "						Trier</p>\n";
echo "				</div>\n";
echo "				<div>\n";
echo "					<i class=\"fa fa-envelope\"></i>\n";
echo "					<p><a href=\"ismailj@hochschule-trier.de\">ismailj@hochschule-trier.de</a></p>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			<div class=\"footer-right\">\n";
echo "				<p class=\"footer-company-about\">\n";
echo "					<span>Über das Unternehmen</span>\n";
echo "					Wir bieten Schulungen und Kurse zum Aufbau von Fähigkeiten in den Bereichen Technologie, Design, Business und Wissenschaft an\n";
echo "					</p>\n";
echo "				<div class=\"footer-icons\">\n";
echo "					<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-youtube\"></i></a>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</footer>\n";
echo "    </div>\n";
echo "</body>\n";
echo "</html>\n";
?>