<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"de\">\n";
echo "\n";
echo "<head>\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style3.css\">\n";
echo "	<link rel=\"stylesheet\" href='https://fonts.googleapis.com/css?family=Poppins'>\n";
echo "	<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\">\n";
echo "	<link rel=\"shortcut icon\" href=\"#\"/>\n";
echo "	<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n";
echo "	<meta charset=\"UTF-8\">\n";
echo "	<title> Gästebuch - Learnhub </title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "	<div class=\"fullscreen\">\n";
echo "		<nav>\n";
echo "			<div class=\"container\">\n";
echo "				<img class=\"logo\" alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "					<a title=\"hier finden sie nützliche Informationen über unsere Organisation\" href=\"proto_about-us.php\">Über uns</a>\n";
echo "					<a title=\"hier können sie zum Shop gelangen\" href=\"proto_shopansicht.php\">Shop</a>\n";
echo "					<a title=\"hier finden sie ihre erstellten Kurse\" href=\"proto_erstellte_kurse.php\">erstellte Kurse</a>\n";
echo "					<a title=\"hier finden sie ihre gekauften Kurse\" href=\"proto_gekaufte_kurse.php\">gekaufte Kurse</a>\n";
echo "					<a title=\"hier gelangen sie zum Gästebuch in dem User Bewertungen für die Seite hinterlassen können\" class=\"active\" href=\"proto_gaestebuch.php\">Gästebuch</a>\n";
echo "					<a title=\"hier können sie sich ausloggen\" href=\"#abmelden\">abmelden</a>\n";
echo "					<a class=\"a-abc\" href=\"#\"><img class=\"img-abc\" src=\"../bilder/abc.png\" alt=\"\" title=\"Font für Legastheniker benutzen\"></a>\n";
echo "			</div>\n";
echo "		</nav>\n";
echo "		<div class=\"bewertung-holder\">\n";
echo "			<h1 class=\"h1bewertung\"> Bewerten Sie unsere Dienstleistungen </h1>\n";
echo "		</div>\n";
echo "\n";
echo "		<a class=\"kerstellung\" id=\"zeige_kommentar_ersteller\" href=\"#\" onClick='(function(){\n";
echo "			document.getElementById(\"zeige_kommentar_ersteller\").style.visibility = \"hidden\";\n";
echo "			document.getElementById(\"kommentar_ersteller\").style.visibility = \"visible\";\n";
echo "		})(); return false;'>Neuen Eintrag verfassen</a>\n";
echo "		<div class=\"kommentarersteller\" id=\"kommentar_ersteller\">\n";
echo "			<form action=\"do.php\">\n";
echo "				<input name=\"title\" placeholder=\"Titel\" /><br>\n";
echo "				<textarea name=\"comment\" class=\"comment\" placeholder=\"Kommentar\"></textarea><br>\n";
echo "				<input name=\"name\" placeholder=\"Name\" /><br>\n";
echo "				<input name=\"addEntry\" type=\"submit\" value=\"Senden\" />\n";
echo "			</form>\n";
echo "		</div>\n";
echo "		<div class=\"comment-container\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Ganz ok</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Hätte mir einige weitere Funktionen gewünscht</p>\n";
echo "				<p class=\"kommentar_info_GB\">Von Manuel Bauer</p>\n";
echo "				<p class=\"kommentar_info_GB\">2. November 2020, 14:07</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Unglaublich gut</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Lernen ging nie einfacher!\n";
echo "				<p>\n";
echo "\n";
echo "				<p class=\"kommentar_info_GB\">Von Sabine Uhrmacher</p>\n";
echo "				<p class=\"kommentar_info_GB\">13. September 2020, 18:17</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "			<div class=\"kommentar_box_GB\">\n";
echo "				<h3>Unverschämtheit</h3>\n";
echo "				<p class=\"kommentar_text_GB\">Ich will mein Geld zurück, aber zackig!!!\n";
echo "				<p>\n";
echo "\n";
echo "				<p class=\"kommentar_info_GB\">Von Basti91</p>\n";
echo "				<p class=\"kommentar_info_GB\">22. Juli 2020, 10:03</p>\n";
echo "			</div>\n";
echo "			<hr class=\"kommentar_seperator_GB\">\n";
echo "		</div>\n";
echo "		<div class=\"pagination_GB\">\n";
echo "			<a href=\"#\">&laquo;</a>\n";
echo "			<a href=\"#\" class=\"active\">1</a>\n";
echo "			<a href=\"#\">2</a>\n";
echo "			<a href=\"#\">3</a>\n";
echo "			<a href=\"#\">&raquo;</a>\n";
echo "		</div>\n";
echo "		<footer class=\"footer-distributed\">\n";
echo "\n";
echo "			<div class=\"footer-left\">\n";
echo "				<img alt=\"Logo der Internetseite. In schwarz geschrieben: Learnhub. Das hub in Learnhub steht vor orangenem Hintergrund.\" src=\"../bilder/learnhublogo.png\">\n";
echo "				<h3>About<span class=\"learn\">Learn</span><span class=\"hub\"><mark>hub</mark></span></h3>\n";
echo "\n";
echo "				<p class=\"footer-company-name\">© 2020 E-Learning Platform. Ltd.</p>\n";
echo "			</div>\n";
echo "\n";
echo "			<div class=\"footer-center\">\n";
echo "				<div>\n";
echo "					<i class=\"fa fa-map-marker\"></i>\n";
echo "					<p><span>Hochschule</span>\n";
echo "						Trier</p>\n";
echo "				</div>\n";
echo "				<div>\n";
echo "					<i class=\"fa fa-envelope\"></i>\n";
echo "					<p><a href=\"ismailj@hochschule-trier.de\">ismailj@hochschule-trier.de</a></p>\n";
echo "					<!-- <i class=\"fa fa-envelope\"></i>\n";
echo "					<p><a href=\"mxtr0669@hochschule-trier.de\">mxtr0669@hochschule-trier.de</a></p>\n";
echo "					<i class=\"fa fa-envelope\"></i>\n";
echo "					<p><a href=\"fachriw@hochschule-trier.de\">fachriw@hochschule-trier.de</a></p> -->\n";
echo "				</div>\n";
echo "			</div>\n";
echo "			<div class=\"footer-right\">\n";
echo "				<p class=\"footer-company-about\">\n";
echo "					<span>Über das Unternehmen</span>\n";
echo "					Wir bieten Schulungen und Kurse zum Aufbau von Fähigkeiten in den Bereichen Technologie, Design, Business und Wissenschaft an\n";
echo "					</p>\n";
echo "				<div class=\"footer-icons\">\n";
echo "					<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\n";
echo "					<a href=\"#\"><i class=\"fa fa-youtube\"></i></a>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</footer>\n";
echo "	</div>\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";
?>