<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"de\">\n";
echo "	<head>\n";
echo "		<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style3.css\"> \n";
echo "		<link href='https://fonts.googleapis.com/css?family=Poppins' rel=\"stylesheet\">\n";
echo "		<meta charset=\"UTF-8\">\n";
echo "		<title> Admin Panel - Learnhub </title>\n";
echo "	</head>\n";
echo "	<body class=\"admin_body\">\n";
echo "	\n";
echo "		<div class=\"admin-wrapper\">\n";
echo "			<h1  > Admin Panel </h1>\n";
echo "			<p  >Angemeldet als: Benutzername</p>\n";
echo "			<hr class=\"admin_hr\">\n";
echo "\n";
echo "			<h3 class=\"admin_function\" > Kurse löschen</h3>\n";
echo "\n";
echo "			<div class=\"admin_function admin_kursL_box\">\n";
echo "				<div class=\"admin_kursL_kurs\">\n";
echo "					<p class=\"p-admin\">Java 101: Das Sprungbrett für Einsteiger</p>	 \n";
echo "					<p class=\"p-admin-bg\">\n";
echo "						<a href=\"../angemeldeter_benutzer_ansicht/proto_kursansicht_nichtteilnehmender-Benutzer.html\" class=\"admin_actionlink\">Zum Kurs</a>\n";
echo "						<a href=\"\" class=\"admin_actionlink\">Löschen</a>\n";
echo "					</p>\n";
echo "\n";
echo "				</div>\n";
echo "\n";
echo "				<div class=\"admin_kursL_kurs\">\n";
echo "					<p class=\"p-admin\">Python Bootcamp: Vom Anfänger zum Profi,in nur 2 Monaten</p>	 \n";
echo "					<p class=\"p-admin-bg\">\n";
echo "						<a href=\"../angemeldeter_benutzer_ansicht/proto_kursansicht_nichtteilnehmender-Benutzer.html\" class=\"admin_actionlink\">Zum Kurs</a>\n";
echo "						<a href=\"\" class=\"admin_actionlink\">Löschen</a>\n";
echo "					</p>\n";
echo "\n";
echo "				</div>\n";
echo "\n";
echo "				<div class=\"admin_kursL_kurs\">\n";
echo "					<p class=\"p-admin\"> Einstieg in die Technologien des WWW</p>	 \n";
echo "					<p class=\"p-admin-bg\">\n";
echo "						<a href=\"../angemeldeter_benutzer_ansicht/proto_kursansicht_nichtteilnehmender-Benutzer.html\" class=\"admin_actionlink\">Zum Kurs</a>\n";
echo "						<a href=\"\" class=\"admin_actionlink\">Löschen</a>\n";
echo "					</p>\n";
echo "\n";
echo "				</div>\n";
echo "\n";
echo "			</div>\n";
echo "\n";
echo "		</div>\n";
echo "		\n";
echo "	</body>\n";
echo "</html>\n";
?>